### ISSUE TITLE
conda install two different versions of `netCDF4`

### ISSUE THREAD

**Issue by daltonkell** [ioos/cc-plugin-ugrid#13]
`conda` seems to install two different versions of `netCDF4` when running the TravisCI builds. While this is not a critical issue, it will undoubtedly come back to bite *someone*.

  - for python2.7, installs v1.4.2:
![py27condanetcdf4](https://user-images.githubusercontent.com/32339201/50926918-40cbff80-1424-11e9-98ee-9a2fb577251c.png)

  - for python3.5, installs v1.4.1:
![py35condanetcdf4](https://user-images.githubusercontent.com/32339201/50926937-4c1f2b00-1424-11e9-995c-624cccad2742.png)

  - for python3.6, installs v1.4.2:
![py36condanetcdf4](https://user-images.githubusercontent.com/32339201/50926973-6527dc00-1424-11e9-840f-dc255325ea3d.png)

Any insight as to why this happens is much appreciated.

**Comment by ocefpaf** [comment]
This is not an issue for `ioos/cc-plugin-ugrid` but a conda question. (Actually a conda-forge question b/c that channel is used.)

The short answer is that conda-forge no longer support Python 3.5, so you'll get old builds there. The long answer entails an explanation about package availability, solver possibilities, and package pinning...
